# Generated by Django 4.2 on 2023-04-14 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default=1, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$'), django.core.validators.EmailValidator()], verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='Пароль'),
        ),
    ]
