# Generated by Django 4.2 on 2023-04-14 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_login_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$')], verbose_name='Логин'),
        ),
    ]
