# Generated by Django 4.2 on 2023-04-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_branch_remove_organization_group_and_more'),
        ('accounts', '0007_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization', to='webapp.organization', verbose_name='Организация'),
        ),
    ]
