# Generated by Django 4.2 on 2023-04-17 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_email_verification_token_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\+996\\d{9}$')], verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='accounts.user', verbose_name='Работник'),
        ),
    ]
