# Generated by Django 4.2 on 2023-04-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_options_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtoken',
            name='token',
        ),
    ]
