# Generated by Django 4.2 on 2023-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_worktime_options_branch_qr_code_and_more'),
        ('accounts', '0013_remove_verificationtoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(related_name='user_organization', to='webapp.organization'),
        ),
    ]
