# Generated by Django 4.2 on 2023-04-08 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('start_time', models.DateTimeField(verbose_name='Дата начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата конца')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Дата начала')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='Дата конца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ')),
                ('organization', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='org_wt', to='webapp.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_worktime', to='accounts.user', verbose_name='Работник')),
            ],
        ),
    ]
