# Generated by Django 4.2 on 2023-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='end_time',
            field=models.DateTimeField(verbose_name='Дата конца'),
        ),
    ]
