# Generated by Django 4.2 on 2023-04-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_organization_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='group',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='group',
                                    to='webapp.group', verbose_name='Группа'),
        ),
    ]
