# Generated by Django 4.2 on 2023-04-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_organization_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Филиала')),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='group',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название Организации'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_wt', to='webapp.organization', verbose_name='Организация'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='organization',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org_wt', to='webapp.branch', verbose_name='Филиал организации'),
            preserve_default=False,
        ),
    ]
