# Generated by Django 4.2 on 2023-04-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_branch_remove_organization_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org_branch', to='webapp.organization', verbose_name='Oрганизациz'),
            preserve_default=False,
        ),
    ]
