# Generated by Django 4.2 on 2023-04-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_verificationtoken_token'),
        ('webapp', '0006_remove_organization_branch_branch_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktime',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='branch',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='QRcode'),
        ),
        migrations.AddField(
            model_name='worktime',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.branch', verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worktime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='webapp.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='accounts.user', verbose_name='Работник'),
        ),
    ]
