# Generated by Django 4.2 on 2023-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_organization_user_organization'),
        ('webapp', '0007_alter_worktime_options_branch_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin',
            field=models.ManyToManyField(blank=True, null=True, related_name='admin_organization', to='accounts.user'),
        ),
    ]
